export type book_type = {
  book_id: number;
  book_name: string;
  short_book_name: string;
  color: string;
  chapter_count: number;
};

const books = [
  {
    book_id: 1,
    book_name: 'Rodzaju',
    short_book_name: 'Rodz.',
    color: '#3b3547',
    chapter_count: 50,
  },
  {
    book_id: 2,
    book_name: 'Wyjścia',
    short_book_name: 'Wyjś.',
    color: '#3b3547',
    chapter_count: 40,
  },
  {
    book_id: 3,
    book_name: 'Kapłańska',
    short_book_name: 'Kapł.',
    color: '#3b3547',
    chapter_count: 27,
  },
  {
    book_id: 4,
    book_name: 'Liczb',
    short_book_name: 'Licz.',
    color: '#3b3547',
    chapter_count: 36,
  },
  {
    book_id: 5,
    book_name: 'Powtórzonego Prawa',
    short_book_name: 'Powt.',
    color: '#3b3547',
    chapter_count: 34,
  },
  {
    book_id: 6,
    book_name: 'Jozuego',
    short_book_name: 'Jozu.',
    color: '#746b84',
    chapter_count: 24,
  },
  {
    book_id: 7,
    book_name: 'Sędziów',
    short_book_name: 'Sędz.',
    color: '#746b84',
    chapter_count: 21,
  },
  {
    book_id: 8,
    book_name: 'Rut',
    short_book_name: 'Rut.',
    color: '#746b84',
    chapter_count: 4,
  },
  {
    book_id: 9,
    book_name: '1 Samuela',
    short_book_name: '1 Sa.',
    color: '#746b84',
    chapter_count: 31,
  },
  {
    book_id: 10,
    book_name: '2 Samuela',
    short_book_name: '2 Sa.',
    color: '#746b84',
    chapter_count: 24,
  },
  {
    book_id: 11,
    book_name: '1 Królów',
    short_book_name: '1 Kr.',
    color: '#746b84',
    chapter_count: 22,
  },
  {
    book_id: 12,
    book_name: '2 Królów',
    short_book_name: '2 Kr.',
    color: '#746b84',
    chapter_count: 25,
  },
  {
    book_id: 13,
    book_name: '1 Kronik',
    short_book_name: '1 Kr.',
    color: '#746b84',
    chapter_count: 29,
  },
  {
    book_id: 14,
    book_name: '2 Kronik',
    short_book_name: '2 Kr.',
    color: '#746b84',
    chapter_count: 36,
  },
  {
    book_id: 15,
    book_name: 'Ezdrasza',
    short_book_name: 'Ezdr.',
    color: '#746b84',
    chapter_count: 10,
  },
  {
    book_id: 16,
    book_name: 'Nehemiasza',
    short_book_name: 'Nehe.',
    color: '#746b84',
    chapter_count: 13,
  },
  {
    book_id: 17,
    book_name: 'Estery',
    short_book_name: 'Este.',
    color: '#746b84',
    chapter_count: 10,
  },
  {
    book_id: 18,
    book_name: 'Hioba',
    short_book_name: 'Hiob.',
    color: '#544c63',
    chapter_count: 42,
  },
  {
    book_id: 19,
    book_name: 'Psalmy',
    short_book_name: 'Psal.',
    color: '#544c63',
    chapter_count: 150,
  },
  {
    book_id: 20,
    book_name: 'Przysłów',
    short_book_name: 'Przy.',
    color: '#544c63',
    chapter_count: 31,
  },
  {
    book_id: 21,
    book_name: 'Kaznodziei',
    short_book_name: 'Kazn.',
    color: '#544c63',
    chapter_count: 12,
  },
  {
    book_id: 22,
    book_name: 'Pieśń nad Pieśniami',
    short_book_name: 'Pieś.',
    color: '#544c63',
    chapter_count: 8,
  },
  {
    book_id: 23,
    book_name: 'Izajasza',
    short_book_name: 'Izaj.',
    color: '#3b3547',
    chapter_count: 66,
  },
  {
    book_id: 24,
    book_name: 'Jeremiasza',
    short_book_name: 'Jere.',
    color: '#3b3547',
    chapter_count: 52,
  },
  {
    book_id: 25,
    book_name: 'Lamentacje',
    short_book_name: 'Lame.',
    color: '#3b3547',
    chapter_count: 5,
  },
  {
    book_id: 26,
    book_name: 'Ezechiela',
    short_book_name: 'Ezec.',
    color: '#3b3547',
    chapter_count: 48,
  },
  {
    book_id: 27,
    book_name: 'Daniela',
    short_book_name: 'Dani.',
    color: '#3b3547',
    chapter_count: 12,
  },
  {
    book_id: 28,
    book_name: 'Ozeasza',
    short_book_name: 'Ozea.',
    color: '#3b3547',
    chapter_count: 14,
  },
  {
    book_id: 29,
    book_name: 'Joela',
    short_book_name: 'Joel.',
    color: '#3b3547',
    chapter_count: 3,
  },
  {
    book_id: 30,
    book_name: 'Amosa',
    short_book_name: 'Amos.',
    color: '#3b3547',
    chapter_count: 9,
  },
  {
    book_id: 31,
    book_name: 'Abdiasza',
    short_book_name: 'Abdi.',
    color: '#3b3547',
    chapter_count: 1,
  },
  {
    book_id: 32,
    book_name: 'Jonasza',
    short_book_name: 'Jona.',
    color: '#3b3547',
    chapter_count: 4,
  },
  {
    book_id: 33,
    book_name: 'Micheasza',
    short_book_name: 'Mich.',
    color: '#3b3547',
    chapter_count: 7,
  },
  {
    book_id: 34,
    book_name: 'Nahuma',
    short_book_name: 'Nahu.',
    color: '#3b3547',
    chapter_count: 3,
  },
  {
    book_id: 35,
    book_name: 'Habakuka',
    short_book_name: 'Haba.',
    color: '#3b3547',
    chapter_count: 3,
  },
  {
    book_id: 36,
    book_name: 'Sofoniasza',
    short_book_name: 'Sofo.',
    color: '#3b3547',
    chapter_count: 3,
  },
  {
    book_id: 37,
    book_name: 'Aggeusza',
    short_book_name: 'Agge.',
    color: '#3b3547',
    chapter_count: 2,
  },
  {
    book_id: 38,
    book_name: 'Zachariasza',
    short_book_name: 'Zach.',
    color: '#3b3547',
    chapter_count: 14,
  },
  {
    book_id: 39,
    book_name: 'Malachiasza',
    short_book_name: 'Mala.',
    color: '#3b3547',
    chapter_count: 4,
  },
  {
    book_id: 40,
    book_name: 'Mateusza',
    short_book_name: 'Mate.',
    color: '#3b3547',
    chapter_count: 28,
  },
  {
    book_id: 41,
    book_name: 'Marka',
    short_book_name: 'Mark.',
    color: '#3b3547',
    chapter_count: 16,
  },
  {
    book_id: 42,
    book_name: 'Łukasza',
    short_book_name: 'Łuka.',
    color: '#3b3547',
    chapter_count: 24,
  },
  {
    book_id: 43,
    book_name: 'Jana',
    short_book_name: 'Jana.',
    color: '#3b3547',
    chapter_count: 21,
  },
  {
    book_id: 44,
    book_name: 'Dzieje',
    short_book_name: 'Dzie.',
    color: '#746b84',
    chapter_count: 28,
  },
  {
    book_id: 45,
    book_name: 'Rzymian',
    short_book_name: 'Rzym.',
    color: '#544c63',
    chapter_count: 16,
  },
  {
    book_id: 46,
    book_name: '1 Koryntian',
    short_book_name: '1 Ko.',
    color: '#544c63',
    chapter_count: 16,
  },
  {
    book_id: 47,
    book_name: '2 Koryntian',
    short_book_name: '2 Ko.',
    color: '#544c63',
    chapter_count: 13,
  },
  {
    book_id: 48,
    book_name: 'Galatów',
    short_book_name: 'Gala.',
    color: '#544c63',
    chapter_count: 6,
  },
  {
    book_id: 49,
    book_name: 'Efezjan',
    short_book_name: 'Efez.',
    color: '#544c63',
    chapter_count: 6,
  },
  {
    book_id: 50,
    book_name: 'Filipian',
    short_book_name: 'Fili.',
    color: '#544c63',
    chapter_count: 4,
  },
  {
    book_id: 51,
    book_name: 'Kolosan',
    short_book_name: 'Kolo.',
    color: '#544c63',
    chapter_count: 4,
  },
  {
    book_id: 52,
    book_name: '1 Tesaloniczan',
    short_book_name: '1 Te.',
    color: '#544c63',
    chapter_count: 5,
  },
  {
    book_id: 53,
    book_name: '2 Tesaloniczan',
    short_book_name: '2 Te.',
    color: '#544c63',
    chapter_count: 3,
  },
  {
    book_id: 54,
    book_name: '1 Tymoteusza',
    short_book_name: '1 Ty.',
    color: '#544c63',
    chapter_count: 6,
  },
  {
    book_id: 55,
    book_name: '2 Tymoteusza',
    short_book_name: '2 Ty.',
    color: '#544c63',
    chapter_count: 4,
  },
  {
    book_id: 56,
    book_name: 'Tytusa',
    short_book_name: 'Tytu.',
    color: '#544c63',
    chapter_count: 3,
  },
  {
    book_id: 57,
    book_name: 'Filemona',
    short_book_name: 'File.',
    color: '#544c63',
    chapter_count: 1,
  },
  {
    book_id: 58,
    book_name: 'Hebrajczyków',
    short_book_name: 'Hebr.',
    color: '#544c63',
    chapter_count: 13,
  },
  {
    book_id: 59,
    book_name: 'Jakuba',
    short_book_name: 'Jaku.',
    color: '#544c63',
    chapter_count: 5,
  },
  {
    book_id: 60,
    book_name: '1 Piotra',
    short_book_name: '1 Pi.',
    color: '#544c63',
    chapter_count: 5,
  },
  {
    book_id: 61,
    book_name: '2 Piotra',
    short_book_name: '2 Pi.',
    color: '#544c63',
    chapter_count: 3,
  },
  {
    book_id: 62,
    book_name: '1 Jana',
    short_book_name: '1 Ja.',
    color: '#544c63',
    chapter_count: 5,
  },
  {
    book_id: 63,
    book_name: '2 Jana',
    short_book_name: '2 Ja.',
    color: '#544c63',
    chapter_count: 1,
  },
  {
    book_id: 64,
    book_name: '3 Jana',
    short_book_name: '3 Ja.',
    color: '#544c63',
    chapter_count: 1,
  },
  {
    book_id: 65,
    book_name: 'Judy',
    short_book_name: 'Judy.',
    color: '#544c63',
    chapter_count: 1,
  },
  {
    book_id: 66,
    book_name: 'Objawienie',
    short_book_name: 'Obja.',
    color: '#3b3547',
    chapter_count: 22,
  },
];

export {books};
